services:
  mariadb:
    image: mariadb:10.11
    container_name: pcmanager_mariadb
    environment:
      MARIADB_DATABASE: pcmanager
      MARIADB_USER: pcmanager
      MARIADB_PASSWORD: pcmanager123
      MARIADB_ROOT_PASSWORD: rootpassword123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -prootpassword123"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
